---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-cu-delhi-server-profile-cu-dell00

resources:
  # SRIOV Configs
  - 00-hook-mcp-wait-job-delhi.yaml
  - 00-delhi-sriov-namespace.yaml
  - 00-delhi-sriov-node-policy.yaml
  - 01-delhi-sriov-networks.yaml
