---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./du-2  

resources:
  - 40-cu-du-cluster-qa-new-bangalore-dell-du.yaml  
  - 50-cu-du-cluster-qa-new-bangalore-dell-du-00-pre.yaml
  - 60-cu-du-cluster-qa-new-bangalore-dell-du-01-post.yaml  
  - 70-cu-du-cluster-qa-new-bangalore-dell-du-02-configs.yaml
