---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./cu-01  

resources:
  - 40-aries-bangalore-dell-cu.yaml  
  - 50-aries-bangalore-dell-cu-00-pre.yaml
  - 60-aries-bangalore-dell-cu-01-post.yaml  
  - 70-aries-bangalore-dell-cu-02-virtualization-configs.yaml
  - 80-aries-bangalore-dell-cu-02-settings.yaml