---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
#    argocd.argoproj.io/sync-wave: "30"
  name: nodes-label-job-sos-worker-1
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.4
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/node
              echo ""
              echo -n "Add node labels"
              until oc wait --selector=node-role.kubernetes.io/ran-cu-bangalore-server-profile-cu-dell00='',kubernetes.io/hostname=sos-worker-1 --for=condition=ready nodes
              do
                echo -n "...still waiting for applying labels"
                oc label node sos-worker-1 node-role.kubernetes.io/ran-cu-bangalore-server-profile-cu-dell00=""
                oc label node sos-worker-1 ran.openshift.io/ocpvirt=""
                oc label node sos-worker-1 ran.openshift.io/sriov=""
                oc label node sos-worker-1 ran.openshift.io/bangalore-sriov-vfio-server-profile-cu-dell00=""
                oc label node sos-worker-1 ran.openshift.io/bangalore-sriov-vfio_a-server-profile-cu-dell00=""
                oc label node sos-worker-1 ran.openshift.io/bangalore-sriov-vfio_b-server-profile-cu-dell00=""

                sleep $SLEEP
              done
              echo "DONE"
          imagePullPolicy: Always
          name: nodes-label-job
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30