---
apiVersion: v1
data:
  mgmtcluster-registry-quay-quay-enterprise.apps.mgmtcluster.altiostar.lan..443: |
    "testcert"
kind: ConfigMap
metadata:
  name: "quay-mgmtcluster-config"
  namespace: openshift-config