---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-du-mysore-server-profile-du-supermicro00

commonAnnotations:
 #argocd.argoproj.io/sync-wave: "20"
 argocd.argoproj.io/sync-options: Prune=false
 argocd.argoproj.io/compare-options: IgnoreExtraneous
# Apps of Apps
resources:
  - 40-aries-mysore-supermicro-du.yaml
  - 50-aries-mysore-supermicro-du-00-pre.yaml
  - 60-aries-mysore-supermicro-du-01-post.yaml
  - 70-aries-mysore-supermicro-du-02-configs.yaml
