---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
#    argocd.argoproj.io/sync-wave: "30"
  name: nodes-label-job-mgmtacm-master-1
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - image: mirrorregistry.rtp.raleigh.ibm.com:5000/ocp4/openshift4:4.6.16-cli
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/node
              echo ""
              echo -n "Add node labels"
              until oc wait --selector=node-role.kubernetes.io/ran-du-mysore-server-profile-du-dell-r640-00='',kubernetes.io/hostname=mgmtacm-master-1 --for=condition=ready nodes
              do
                echo -n "...still waiting for applying labels"
                oc label node mgmtacm-master-1 node-role.kubernetes.io/ran-du-mysore-server-profile-du-dell-r640-00=""
                oc label node mgmtacm-master-1 ran.openshift.io/mysore-sriov-vfio-server-profile-du-dell-r640-00=""
                oc label node mgmtacm-master-1 ran.openshift.io/mysore-sriov-vfio_ar-server-profile-du-dell-r640-00=""
                oc label node mgmtacm-master-1 ran.openshift.io/mysore-sriov-netdevice-server-profile-du-dell-r640-00=""
                oc label node mgmtacm-master-1 ran.openshift.io/mysore-sriov-netdevice_fh-server-profile-du-dell-r640-00=""
                oc label node mgmtacm-master-1 ran.openshift.io/mysore-ptp-server-profile-du-dell-r640-00=""
                oc label node mgmtacm-master-1 ran.openshift.io/n3k=""
                oc label node mgmtacm-master-1 ran.openshift.io/ptp=""
                oc label node mgmtacm-master-1 ran.openshift.io/sriov=""

                sleep $SLEEP
              done
              echo "DONE"
          imagePullPolicy: Always
          name: nodes-label-job
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30